### ISSUE TITLE
腾讯云函数创建在线云函数服务(nodejs) 依赖包不能自动导入

### ISSUE THREAD

**Issue by MrZhDong** [tencentyun/scf-java-libs#3]
1、云函数创建服务，不能自动引入依赖的包，测试的依赖为 require('axios')，临时解决方案为下载到本地，手动引入依赖包，重新打包上传可以解决
2、云函数的引导实例版本较低，很多示例显示不一致
如：a、介绍文档 在创建云函数服务有自动引包的选项，目前无此选项
![图片](https://user-images.githubusercontent.com/39332805/68171821-3e88f200-ffb0-11e9-8e7c-1eb989cf83cd.png)
    b、项目部署 scf deploy 所有参数为非必填，但是不填却提示语法不对。另外https://cloud.tencent.com/developer/article/1472156 这篇文章的
 # 打包
scf package -t template.yaml
Generate deploy file 'deploy.yaml' success

# 发布
scf deploy -t deploy.yaml
Deploy function 'wework-robot' success 目前命令不支持，建议完善一下

**Comment by alfredhuang211** [comment]
nodejs 相关，和当前的 java lib 无关联
